apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  # These labels for deployment resource. 
  labels:
    app: nginx
    tier: frontend
    purpose: deployment
spec: 
  # Modify the replicas number according to our use case.
  replicas: {{ .Values.deployment.replicas }} #assume this will change
  selector:
  # Replicaset use these labels to find the pods for creating desired number of replicas.
    matchLabels:
      app: nginx
      tier: frontend
      purpose: deployment
  # Pod Template
  template:
    metadata:
      labels: 
        app: nginx
        tier: frontend
        purpose: deployment
    spec: 
      containers:
      - name: nginx
        image: nginx:{{ .Values.deployment.imageVersion }} #image version frequently changes
        ports:
        - containerPort: 80